### ISSUE TITLE
Which syntax for "Notification's excluded directories"?

### ISSUE THREAD

**Issue by m0urs** [stremlau/html5_notifier#31]
How do I need to specify the folder names in the setting "Notification's excluded directories"? I tried several types like

Folder1, Folder2
"Folder1", "Folder"
Folder1; Folder2
Folder1:Folder2

but I do get notifications all the time also for these folders?

**Comment by stremlau** [comment]
Just separate them with a comma: Folder1, Folder2

**Comment by m0urs** [comment]
Hm, I just did some more tests. And now it works. Maybe I did something wrong before. Thanks a lot.
