### ISSUE TITLE
Possibility to activate it for all users

### ISSUE THREAD

**Issue by scroom** [stremlau/html5_notifier#34]
As described above. I would like to activate it for all users.

**Comment by rmcaninch** [comment]
You can configure default user preferences. Check the documentation or look at the plugin code for which ones need set. This would be for new users. 

See the roundcube bin/moduserprefs.sh to set it for existing users.

**Comment by scroom** [comment]
@rmcaninch thanks for your hints. I've moved to the build-in-plugin newmail_notifier, because the settings were really easy, just had to configure the config.inc.php of the plugin and it worked as wanted. I'm hoping as well that this build-in-plugin will be supported by future updates.
