### ISSUE TITLE
mailbox filter does not work if "don't show mailbox" is selected

### ISSUE THREAD

**Issue by alpianon** [stremlau/html5_notifier#42]
Even if one puts some directories in "Notification's excluded directories" settings field, if "don't show mailbox" is selected, notifications are still displayed for new messages in such directories. 
Moreover,  "Notification's excluded directories" settings field must be filled in different ways if "show short mailbox" or instead "show full mailbox" is selected (only the subdir name in the first case; the full path in the second case).

**Comment by stremlau** [comment]
Thank you, I merged it and created a new release
