### ISSUE TITLE
Including the plugin version in 'composer.json'

### ISSUE THREAD

**Issue by ner00** [stremlau/html5_notifier#47]
It's useful to be able to click RC's 'About' link and see what version the plugin is on, helps knowing if an update is in order.

As stated in [patch](https://github.com/ner00/html5_notifier/commit/75d6652e852f2c388d7a52abbe003a42d6f0e352) proposal: https://github.com/ner00/html5_notifier/blob/patch-1/composer.json#L8

**Comment by stremlau** [comment]
Thank you!
